### ISSUE TITLE
Requisitos Funcionais

### ISSUE THREAD

**Issue by MarceloMoreiraNunes** [ICEI-PUC-Minas-PMV-SI/pmv-si-2021-1-e1-proj-web-t1-larbem#11]
.

**Comment by MarceloMoreiraNunes** [comment]
Requisitos Funcionais

Permitir o cadastramento do doador;

Permitir acesso aos balancetes pata comprovação dos gastos;

Permitir acesso à lista dos doadores;

**Comment by RafaelaSantos** [comment]
Últimos ajustes dos requisitos funcionais foram realizados pelo Vinicius.
