### ISSUE TITLE
Requisitos Não Funcionais

### ISSUE THREAD

**Issue by viniciusclisboa** [ICEI-PUC-Minas-PMV-SI/pmv-si-2021-1-e1-proj-web-t1-larbem#12]

**Comment by RafaelaSantos** [comment]
Atividade da etapa atual:  - Tirar o Requisito não-funcional = 4,  ordenar os requisitos não funcionais restantes pela Prioridade (Alta, média e baixa) e após isso ajustar os IDs dos requisitos não funcionais.

**Comment by MarceloMoreiraNunes** [comment]
Concluído. #12
