### ISSUE TITLE
incorporar Google Maps para localização do LARBEM

### ISSUE THREAD

**Issue by viniciusclisboa** [ICEI-PUC-Minas-PMV-SI/pmv-si-2021-1-e1-proj-web-t1-larbem#39]
#39  incorporado localização Google Maps

**Comment by MarceloMoreiraNunes** [comment]
#39 Incorporado Google Maps para localização do LARBEM.

**Comment by MarceloMoreiraNunes** [comment]
<div style="overflow:hidden;width: 300px;position: relative;"><iframe width="300" height="300" src="https://maps.google.com/maps?width=300&amp;height=300&amp;hl=en&amp;q=Rua%20General%20Mena%20Barreto%2C%20Cordeiro%2C%20Recife%20-%20PE+(LARBEM)&amp;ie=UTF8&amp;t=k&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;"><small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by <a href="https://embedgooglemaps.com/en/">embedgooglemaps EN</a> & <a href="https://enablejavascript.co">How to enable javascript</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><br />

**Comment by MarceloMoreiraNunes** [comment]
HTML

<!DOCTYPE html>

<html>
<head>
<title>Google Mapas</title>
</head>

<body>
        <section class="mapas">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3950.5611586295504!2d-34.929548985681!3d-8.044096282564417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7ab1912bef55919%3A0x7f4c033fe4a34931!2sR.%20Gen.%20Mena%20Barreto%2C%2097%20-%20Cordeiro%2C%20Recife%20-%20PE%2C%2050731-060!5e0!3m2!1spt-BR!2sbr!4v1622748418506!5m2!1spt-BR!2sbr" width="600" height="150" frameborder="0" style="border:0;" allowfullscreen></iframe>
        </section>
</body>
    </html>

**Comment by MarceloMoreiraNunes** [comment]
CSS

.mapas{
	text-align: center;
	wiidth: 100%
}
